### ISSUE TITLE
Parse string with tasks as subtasks

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/txt#3]
https://github.com/epogrebnyak/txt/blob/master/main.py#L78-L100

**Comment by arwer13** [comment]
doc2 и ds не соответствуют друг другу, поэтому assert не проходит: https://github.com/epogrebnyak/txt/commit/276e89224122f8b1c7fb2541dcbd31d076c7f4c5

**Comment by epogrebnyak** [comment]
Далее:
- [x] рефакторим `parse_tasks(doc)` https://github.com/epogrebnyak/txt/blob/master/main.py#L108-L125, выглядит навороченно
- [x] можно ли обойтись без deep.copy()?
- [x] использовать `startswith()` в коде проверок задачи, подзадачи

**Comment by arwer13** [comment]
Порефакторил с упором на лаконичность https://github.com/epogrebnyak/txt/commit/9dd8924750da2ba2642b528a611b64dd392f5168

**Comment by arwer13** [comment]
Исправил разбор задачи без подзадач https://github.com/epogrebnyak/txt/commit/bb2afba11682ce65b7713779b3ed593ce03d33ec

**Comment by epogrebnyak** [comment]
Тест проходит, код более или менее понятный. Просьба прокомментриуйте `lines(doc)` https://github.com/epogrebnyak/txt/blob/master/main.py#L101-L105

**Comment by arwer13** [comment]
Комметарии про `lines(doc)`
https://github.com/epogrebnyak/txt/commit/4d260dea14f9a3d8a3a03cb95cdedff758bd5cda

**Comment by arwer13** [comment]
Лушее выделение строк с задачами/подзадачами
https://github.com/epogrebnyak/txt/commit/c62bcd4a84f1a160c463433109e4bda9fa8dc4dc
